<?php

return [
    'key'                   => 'group_643ff770cb1b9',
    'title'                 => __('Sponsor Info', 'nvis-study-abroad'),
    'menu_order'            => 0,
    'position'              => 'acf_after_title',
    'style'                 => 'seamless',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'active'                => true,
    'description'           => '',
    'location'              => [
        [
            [
                'param'    => 'taxonomy',
                'operator' => '==',
                'value'    => static::TAXONOMY,
            ],
        ],
    ],
    'fields' => [
        [
            'key'               => 'field_643fe8baa9ab5',
            'label'             => 'Program Content',
            'name'              => 'sponsor_program_content',
            'aria-label'        => '',
            'type'              => 'wysiwyg',
            'instructions'      => __('Add the following to the program content section. Displayed after the brochure sections if present.','nvis-study-abroad'),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
                'width' => '',
                'class' => '',
                'id'    => '',
            ],
            'default_value' => '',
            'tabs'          => 'all',
            'toolbar'       => 'basic',
            'media_upload'  => 1,
            'delay'         => 0,
        ],              
        [
            'key'               => 'field_64dbb63e5046a',
            'label'             => __('Program Dates Override', 'nvis-study-abroad'),
            'name'              => 'program_dates',
            'aria-label'        => '',
            'type'              => 'repeater',
            'instructions'      => __('Replaces the dates section on all programs from this sponsor', 'nvis-study-abroad'),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
                'width' => '',
                'class' => '',
                'id'    => '',
            ],
            'layout'        => 'block',
            'pagination'    => 0,
            'min'           => 0,
            'max'           => 0,
            'collapsed'     => 'field_64dbb6cd7e2b6',
            'button_label'  => __('Add Term Dates', 'nvis-study-abroad'),
            'rows_per_page' => 20,
            'sub_fields'    => [
                [
                    'key'               => 'field_64dbb6cd7e2b6',
                    'label'             => __('Term', 'nvis-study-abroad'),
                    'name'              => 'term',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'   => '',
                    'maxlength'       => '',
                    'placeholder'     => '',
                    'prepend'         => '',
                    'append'          => '',
                    'parent_repeater' => 'field_64dbb63e5046a',
                ],
                [
                    'key'               => 'field_64dbb6d7669c6',
                    'label'             => __('Year', 'nvis-study-abroad'),
                    'name'              => 'year',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'   => '',
                    'maxlength'       => '',
                    'placeholder'     => '',
                    'prepend'         => '',
                    'append'          => '',
                    'parent_repeater' => 'field_64dbb63e5046a',
                ],
                [
                    'key'               => 'field_64dbb6e4d439c',
                    'label'             => __('Application Deadline', 'nvis-study-abroad'),
                    'name'              => 'app_deadline_date',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => __('Enter a date in the format YYYY-MM-DD, or some descriptive text.', 'nvis-study-abroad'),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'parent_repeater' => 'field_64dbb63e5046a',
                ],
                [
                    'key'               => 'field_64dbb6f439833',
                    'label'             => __('Decision Date', 'nvis-study-abroad'),
                    'name'              => 'decision_date',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => __('Enter a date in the format YYYY-MM-DD, or some descriptive text.', 'nvis-study-abroad'),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'parent_repeater' => 'field_64dbb63e5046a',
                ],
                [
                    'key'               => 'field_64dbb70853bfc',
                    'label'             => __('Start Date', 'nvis-study-abroad'),
                    'name'              => 'start_date',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => __('Enter a date in the format YYYY-MM-DD, or some descriptive text.', 'nvis-study-abroad'),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'parent_repeater' => 'field_64dbb63e5046a',
                ],
                [
                    'key'               => 'field_64dbb714151b6',
                    'label'             => __('End Date', 'nvis-study-abroad'),
                    'name'              => 'end_date',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => __('Enter a date in the format YYYY-MM-DD, or some descriptive text.', 'nvis-study-abroad'),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'parent_repeater' => 'field_64dbb63e5046a',
                ],
            ],
        ],
        [
            'key'               => 'field_64dbb814d8c35',
            'label'             => __('Program Brochure Override', 'nvis-study-abroad'),
            'name'              => 'program_brochure_sections',
            'aria-label'        => '',
            'type'              => 'repeater',
            'instructions'      => __('Replaces the brochure sections on all programs from this sponsor.', 'nvis-study-abroad'),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
                'width' => '',
                'class' => '',
                'id'    => '',
            ],
            'layout'        => 'block',
            'pagination'    => 0,
            'min'           => 0,
            'max'           => 0,
            'collapsed'     => 'field_64dbb84f4ab11',
            'button_label'  => __('Add Section', 'nvis-study-abroad'),
            'rows_per_page' => 20,
            'sub_fields'    => [
                [
                    'key'               => 'field_64dbb84f4ab11',
                    'label'             => __('Title', 'nvis-study-abroad'),
                    'name'              => 'title',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'   => '',
                    'maxlength'       => '',
                    'placeholder'     => '',
                    'prepend'         => '',
                    'append'          => '',
                    'parent_repeater' => 'field_64dbb814d8c35',
                ],
                [
                    'key'               => 'field_64dbb858dbe67',
                    'label'             => __('Slug', 'nvis-study-abroad'),
                    'name'              => 'slug',
                    'aria-label'        => '',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'   => '',
                    'maxlength'       => '',
                    'placeholder'     => '',
                    'prepend'         => '',
                    'append'          => '',
                    'parent_repeater' => 'field_64dbb814d8c35',
                ],
                [
                    'key'               => 'field_64dbb8681fc00',
                    'label'             => __('Content', 'nvis-study-abroad'),
                    'name'              => 'content',
                    'aria-label'        => '',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => [
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ],
                    'default_value'   => '',
                    'tabs'            => 'all',
                    'toolbar'         => 'full',
                    'media_upload'    => 1,
                    'delay'           => 1,
                    'parent_repeater' => 'field_64dbb814d8c35',
                ],
            ],
        ], 
    ]
];
