<?php 

return [
    'key'    => 'group_63cae7b6d86a4',
    'title'  => __('Location Info', 'nvis-study-abroad'),
    'menu_order'            => 0,
    'position'              => 'acf_after_title',
    'style'                 => 'seamless',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'active'                => true,
    'description'           => '',
    'location'              => [
        [
            [
                'param'    => 'taxonomy',
                'operator' => '==',
                'value'    => static::TAXONOMY,
            ],
        ],
    ],
    'fields' => [
        [
            'key' => 'field_63d81f5f47a67',
            'label' => 'Location Type',
            'name' => 'location_type',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_63d819c1ee776',
            'label' => 'Geo Coordinates',
            'name' => 'geo_coords',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('Latitude,Longitude in <a href="https://en.wikipedia.org/wiki/Decimal_degrees" target="_blank">Decimal Degrees</a> (e.g. Rio is `-22.90278,-43.2075`).', 'nvis-study-abroad'),
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key'           => 'field_63cae7cd82601',
            'label'         => __('Featured Image', 'nvis-study-abroad'),
            'name'          => 'featured_image',
            'type'          => 'image',
            'instructions'  => '',
            'return_format' => 'id',
            'preview_size'  => 'medium',
            'library'       => 'all'
        ],
        [
            'key'               => 'field_63cae7d9dff59',
            'label'             => __('Header Background Image', 'nvis-study-abroad'),
            'name'              => 'header_background',
            'type'              => 'image',
            'instructions'      => __('The background image of the archive page header (Tuxedo Mode only).', 'nvis-study-abroad'),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => 'present-mode-full',
                'id'    => '',
            ],
            'return_format' => 'id',
            'preview_size'  => 'medium',
            'library'       => 'all',
            'min_width'     => '',
            'min_height'    => '',
            'min_size'      => '',
            'max_width'     => '',
            'max_height'    => '',
            'max_size'      => '',
            'mime_types'    => '',
        ],
    ],
];
